import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "@/providers/NextAuthProvider";
import { isTokenExpired, isTokenValidFromBackend } from "@/lib/auth";
import Logout from "@/components/Logout";
import { ApolloClientProvider } from "@/providers/ApolloClientProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { MaterialUIProvider } from "@/providers/MaterialUIProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Academic Assistant",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  if (session && !(await isTokenValidFromBackend(session!))) {
    return <Logout />;
  }

  if (await isTokenExpired(session!)) {
    return <Logout />;
  }

  return (
    <NextAuthProvider session={session!}>
      <ApolloClientProvider uri={process.env.GRAPHQL_URL!}>
        <MaterialUIProvider>
          <html lang="en">
            <head>
              <meta
                name="viewport"
                content="initial-scale=1, width=device-width"
              />
            </head>
            <body className={inter.className}>{children}</body>
          </html>
        </MaterialUIProvider>
      </ApolloClientProvider>
    </NextAuthProvider>
  );
}
